# Generated by Django 2.2.13 on 2020-10-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Beverages', 'Bevarages'), ('Dairy', 'Dairy'), ('Bakery', 'Bakery'), ('Flours', 'Flours')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('available_quantity', models.IntegerField()),
            ],
        ),
    ]
