# Generated by Django 2.2.13 on 2020-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_orderdetails_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
