# Generated by Django 2.2.13 on 2020-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20201103_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateField(),
        ),
    ]
