# Generated by Django 3.1.1 on 2020-10-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20201003_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated',
        ),
    ]
