# Generated by Django 2.2.13 on 2020-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20201103_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
